Fixing CI for publish on GH pages
MetaMask/template-snap-monorepo pull request #29
Opened 2023-01-28 20:49 UTC by immortal-tofu

- Typo in source-directory
- Missing env variable

2023-01-30 09:59 UTC, Mrtenz commented
Thanks! Can you please rebase to the latest commit on `main`, in order to make CI pass? There was an issue with the "Require additional reviewer for releases" workflow that we've removed now.

2023-03-05 15:11 UTC, GuillaumeRx requested changes

2023-03-05 15:11 UTC, GuillaumeRx commented on .github/workflows/publish-release.yml
> +          source-directory: packages/site/dist
Gatsby creates the production build under `public`.

```suggestion
          source-directory: packages/site/public
```

2023-03-07 16:10 UTC, GuillaumeRx approved these changes

2023-03-07 16:10 UTC, merged