Add `Buffer`, a common dependency, to global scope
MetaMask/template-snap-monorepo pull request #35
Opened 2023-03-29 04:11 UTC by ziad-saab

This PR adds `Buffer` to the global scope by importing it from a polyfill.

2023-03-29 04:14 UTC, ziad-saab commented
Why we can't just add the line `globalThis.Buffer = xxx` to the `index.ts` of the snap:

`import`s are evaluated "statically" in theory. Even in transpiled code they're executed first, even before source code that is "above" them in the module. By putting the `globalThis` code in its own module, and loading that module first, we ensure that `Buffer` is available everywhere, including in other `import`s from `index.ts`.

2023-03-29 08:29 UTC, Mrtenz commented on packages/snap/src/buffer-fix.ts
Have you verified that this works with dependencies using `Buffer`?

2023-03-29 09:02 UTC, ritave commented
> Why we can't just add the line `globalThis.Buffer = xxx` to the `index.ts` of the snap:
> 
> `import`s are evaluated "statically" in theory. Even in transpiled code they're executed first, even before source code that is "above" them in the module. By putting the `globalThis` code in its own module, and loading that module first, we ensure that `Buffer` is available everywhere, including in other `import`s from `index.ts`.

Adding this as a comment to the fix file will be cool

2023-03-29 09:34 UTC, FrederikBolding commented on packages/snap/src/index.ts
> +import './buffer-fix';
Is it cleaner to do this in the `snap.config.js` so we don't have to have this in our source code?

e.g.

```
module.exports = {
  cliOptions: {
    src: './src/index.ts',
    port: 8080,
  },
  bundlerCustomizer: (bundler) => {
    const through = require('through2');
    bundler.transform(function () {
      let data = '';
      return through(
        function (buf, _enc, cb) {
          data += buf;
          cb();
        },
        // eslint-disable-next-line consistent-return
        function (cb) {
          this.push("globalThis.Buffer = require('buffer/').Buffer;");
          this.push(data);
          cb();
        },
      );
    });
  },
};
```

2023-03-31 10:00 UTC, Mrtenz requested changes

2023-03-31 10:00 UTC, Mrtenz commented on packages/snap/snap.config.js
> +    const through = require('through2');
Couldn't this just be imported at the top of this file?

2023-03-31 10:00 UTC, Mrtenz commented on packages/snap/snap.config.js
> +        function (buf, _enc, cb) {
```suggestion
        function (buffer, _encoding, callback) {
```

2023-03-31 10:00 UTC, Mrtenz commented on packages/snap/snap.config.js
> +        // eslint-disable-next-line consistent-return
Is this needed?

2023-04-29 21:09 UTC, Mrtenz requested changes

2023-04-29 21:09 UTC, Mrtenz commented on packages/snap/snap.config.js
> +          cb();
```suggestion
        function (callback) {
          this.push("globalThis.Buffer = require('buffer/').Buffer;");
          this.push(data);
          callback();
```

2023-04-30 21:08 UTC, Mrtenz approved these changes

2023-05-01 14:48 UTC, merged